# Example to demonstrate Marketplace operartor install
# Install Memsql. Note: namespace should exist in the cluster

apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: memsql-og-redhat-marketplace
  namespace: memsql-trial
spec:
  targetNamespaces:
  - memsql-trial
