---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-redhat-marketplace
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: redhat-marketplace-operator
  namespace: openshift-redhat-marketplace
spec:
  targetNamespaces:
  - openshift-redhat-marketplace
---
apiVersion: v1
kind: Secret
metadata:
  name: rhm-operator-secret
  namespace: openshift-redhat-marketplace
data:
  IBM_COS_READER_KEY: V0JhSzdN0bWNOcVpldGtMYjEtd1dWZlRTR0lBbUE3VlNheC1BX19EZjY5bm4=
  BUCKET_NAME: NWU2MTYzNjljZNWE0MTcwMDEzZTA2NDUz
  IBM_COS_URL: aHR0cHM6Ly9zMy51cy1lYNXN0LmNsb3VkLW9iamVjdC1zdG9yYWdlLmFwcGRvbWFpbi5jbG91ZA==
  RAZEE_DASH_ORG_KEY: b3JnQXBpS2V5NLTYzYzc2OGVhLTNjZDMtNDA3My05YTk3LWIyNDE0YzgwYzA5Yg==
  CHILD_RRS3_YAML_FILENAME: Y2hpbGRSUlMzNLnlhbWw=
  RAZEE_DASH_URL: aHR0cHM6Ly9tYXJrZXRwNbGFjZS5yZWRoYXQuY29tL2FwaS9jb2xsZWN0b3IvdjI=
  FILE_SOURCE_URL: aHR0cHM6Ly9zMyN51cy5jbG91ZC1vYmplY3Qtc3RvcmFnZS5hcHBkb21haW4uY2xvdWQvcmVkaGF0LW1hcmtldHBsYWNlL3JhemVlLWlv
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
 name: redhat-marketplace-operator
 namespace: openshift-redhat-marketplace
 labels:
    razee/watch-resource: lite
spec:
 channel: stable
 installPlanApproval: Automatic
 name: redhat-marketplace-operator
 source: certified-operators
 sourceNamespace: openshift-marketplace