apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: mongodb-enterprise-advanced-ibm-rhmp
  namespace: mongodb-trial
spec:
  channel: stable
  installPlanApproval: Automatic
  name: mongodb-enterprise-advanced-ibm-rhmp
  source: redhat-marketplace
  sourceNamespace: openshift-marketplace
#  startingCSV: mongodb-enterprise-advanced-ibm.v1.6.1